### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by dimqua** [CurrencyConverterCalculator/android#9]
I think it'd be nice to add the app to [F-Droid](https://f-droid.org/). @mustafaozhan are you OK with it?
See also: https://gitlab.com/fdroid/rfp/issues/764

**Comment by IzzySoft** [comment]
For that it'd also be nice to have a flavor that doesn't require the proprietary [Play Services Ads](https://github.com/CurrencyConverterCalculator/android/blob/master/app/build.gradle#L74) and [Crashlytics](https://github.com/CurrencyConverterCalculator/android/blob/master/app/build.gradle#L77), which are no-goes for F-Droid.

Possible? Thanks in advance!

**Comment by mustafaozhan** [comment]
Hello,

Thank you for your message, Of course I would like to do that, I have some questions about it can we continue with email mr.mustafa.ozhan@gmail.com

**Comment by IzzySoft** [comment]
Sorry, but no. My mail server will "reject" mails coming from gmail.com (I don't want a bunch of 3rd parties reading my mails). What's so secret about your questions they cannot be discussed in an issue? Not sure, but if it's really needed, doesn't Github offer making an issue "confidential"?

**Comment by dimqua** [comment]
@mustafaozhan you don't necessarily need to do it by yourself, the F-Droid team can add your apps (sooner or later), but (at least) they need your public approval of doing so.

**Comment by mustafaozhan** [comment]
@IzzySoft It is not secret I just didn't want to have a long conversation here 😄 As @dimqua guessed already, my question is about the process of building and adding app to F-Droid.

How is the way for dealing it ? For example right now latest apk in Google Play Store is approximately 5-6 commits behind of my repository in GitHub. Is F-Droid using latest commit of master branch ? 

Secondly I do not wanna create second flavor for F-Droid to without Play Services Ads and Crashlytics, I want to have same apk on both platform also collect and keep track statistic of my Apps via Fabric Crashlytics.

**Comment by IzzySoft** [comment]
First hint is to https://f-droid.org/docs – where you should find all those details (well, happy reading, it's quite a lot :wink:) So in short:

* you use [tags](https://github.com/CurrencyConverterCalculator/android/releases), and so do we. Tags are marking releases – everything in between could be "not that stable".
* not possible. GMS, Crashlytics & Co are proprietary (not FOSS), so they are show-stoppers for F-Droid. If you insist on analytics, AFAIK e.g. ACRA is accepted by F-Droid – though that still will ean to flag your app with the "Tracking" AntiFeature.

**Comment by IzzySoft** [comment]
Ugh. Would you at least attache the APK file to its corresponding release tag, so I could add it to my repo until remaining issues have been sorted out?

**Comment by mustafaozhan** [comment]
Hello,

You can find the apk which is in the store now from [here](https://www.dropbox.com/s/1gs5zam2cv2nznk/app-release.apk?dl=0). This apk is how is it in the Play store. Nowadays I am trying to write backed for this app in order to increase number of currencies 32 to 170 + so that's why project is in big mess now.

**Comment by IzzySoft** [comment]
Sorry, I cannot grab from Dropbox – and others are unlikely to find it there. Why not simply attaching it to its corresponding tag here?

**Comment by mustafaozhan** [comment]
Because some of the files not included in repository for privacy also current master is with new API integration which is not fully supported yet none of the commit has the same version with the real-time app.  I am not able to put apk to here. It says We do not support that file type.

**Comment by mustafaozhan** [comment]
[apk.zip](https://github.com/CurrencyConverterCalculator/android/files/2705518/apk.zip)
wait I found a workaround

**Comment by IzzySoft** [comment]
> I am not able to put apk to here. It says We do not support that file type.

No idea where you've tried and how, but there are plenty of app repos who do attach it there. I guess that's done when [editing the tag to make it a release](https://github.com/CurrencyConverterCalculator/android/releases) (e.g. when you add a changelog or other release notes). Guess that's what you just found out. I'll then wait for that release, so I can setup everything on my end properly. Please let me know here then when it's ready. And please attach it there as plain `.apk`, not as `*.zip`. Thanks!

**Comment by mustafaozhan** [comment]
Please find the apk file at release. It is signed apk and +170 currencies implemented. Do not try to compile with source code because API private keys are not included in git.

Regards.

**Comment by mustafaozhan** [comment]
For both of app release apks added. I do not know how we will give update in future but I will contiune to create releases when apps have big changes so you can follow the apks like this ? is it okay for you?

**Comment by IzzySoft** [comment]
Thanks, Mustafa! I just grabbed the first one and checked it. As stated above, it still comes with too many trackers even for my repo:

* GMS
* Google Ads
* Doubleclick
* Crashlytics

While rules for [my repo](https://apt.izzysoft.de/fdroid/repo) are certainly more relax than for the official one, this unfortunately is even too much for that: more than 2 trackers I don't accept. Could you do with less trackers (best without of course)?

As for updates: As long as you'd create new tags with the corresponding APK attached, my auto-updater would grab them (usually within 24h).

**Comment by IzzySoft** [comment]
@mustafaozhan any chance to get a FOSS flavor coming without those 4, so [inclusion with the official repo](https://gitlab.com/fdroid/rfp/issues/764) can be completed? Please let us know (even if the answer is no).

**Comment by mustafaozhan** [comment]
For both of app I decided to not put in F-Droid because I do not want a variant without `Fabric` and `AdMob`. I uploaded apk because  there are only 2 tracker but as i can see your scan recognising AdMob as 2 different tracker `GMS` and `Google Ads`. Also I do not have any idea from where `Doubleclick` came from

**Comment by IzzySoft** [comment]
I guess AdMob includes the other two automatically nowadays (though in the past it were different "services"). And GMS comes in as at least one of them relies on GMS (my guess is AdMob; AFAIR AdMob services are integrated with GMS).

A pity you won't offer a tracking-free version. For privacy oriented users, those are no-gos. So I take it I can close the F-Droid ticket (just done). If you decide otherwise, please update this ticket here (or the other at F-Droid) and we check again.
